name: sheraa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  badges: null
  basic_utils: ^3.0.2
  bubble_bottom_bar: ^2.0.0
  carousel_slider: null
  chewie: any
  cloud_firestore: ^3.1.18
  country_list_pick: ^1.0.1+6
  cupertino_icons: ^1.0.2
  device_info: null
  dio: null
  extended_image: ^6.1.0
  file_picker: ^3.0.1
  firebase_auth: ^3.3.20
  firebase_dynamic_links: ^3.0.2
  firebase_messaging: null
  flutter:
    sdk: flutter
  flutter_local_notifications: null
  flutter_localizations:
    sdk: flutter
  flutter_offline: null
  flutter_slidable: ^0.6.0
  flutter_spinkit: null
  get_it: ^7.2.0
  hidden_drawer_menu: null
  http: ^0.13.1
  image_editor: null
  image_gallery_saver: ^1.7.1
  image_picker: null
  image_size_getter: ^2.1.2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  logging: ^1.0.1
  oktoast: ^3.1.5
  open_file: ^3.2.0
  path_provider: any
  percent_indicator: ^4.0.0
  permission_handler: ^10.2.0
  photo_view: null
  pin_code_fields: ^7.4.0
  pointycastle: ^3.0.0-nullsafety.2
  provider: null
  pull_to_refresh: ^2.0.0
  random_string: 2.1.0
  screenshot: ^1.2.3
  share: null
  share_plus: ^2.1.4
  shared_preferences: null
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_pdfviewer: ^19.1.57-beta
  toast: null
  url_launcher: null
  validators: null
  video_player: ^2.4.2
  video_player_web: ^2.0.10
  webview_flutter: ^0.3.24

dependency_overrides:
  url_launcher_web: 2.0.6

dev_dependencies:
  flutter_launcher_icons: null
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - i18n/en.json
    - i18n/ar.json
    - assets/CountryCodes.json
    - assets/images/logo.png
    - assets/images/map.png
    - assets/images/saudi-arabia.png
    - assets/images/united-arab-emirates.png
    - assets/images/kuwait.png
    - assets/images/MAN.png
    - assets/images/women.png
    - assets/images/checkbox.png
    - assets/images/home.png
    - assets/images/notification.png
    - assets/images/messages.png
    - assets/images/menu.png
    - assets/images/slider.png
    - assets/images/user.png
    - assets/images/arrow_simple.png
    - assets/images/wallet.png
    - assets/images/star.png
    - assets/images/mouse.png
    - assets/images/subtitle.png
    - assets/images/lovely.png
    - assets/images/search-status.png
    - assets/images/ranking.png
    - assets/images/crown.png
    - assets/images/page.png
    - assets/images/people.png
    - assets/images/global.png
    - assets/images/moon.png
    - assets/images/calling.png
    - assets/images/user-add.png
    - assets/images/box.png
    - assets/images/coin.png
    - assets/images/menu-dots.png
    - assets/images/info.png
    - assets/images/add-circle.png
    - assets/images/saudi-arabia.png
    - assets/images/search.png
    #- assets/images/1.png
    - assets/images/max.png
    - assets/images/centerpoint.png
    - assets/images/namshi.png
    - assets/images/profile.png
    - assets/images/info.png
    - assets/images/people.png
    - assets/images/diamonds.png
    - assets/images/gallery_add.png
    - assets/images/video.png
    - assets/images/question-fill.png
    - assets/images/white-car.png
    - assets/images/car.png
    - assets/images/check.png
    - assets/images/house.png
    - assets/images/house-2.png
    - assets/images/buildings.png
    - assets/images/round_circle.png
    - assets/images/checked.png
    - assets/images/add-circle-white.png
    - assets/images/flash.png
    - assets/images/microphone.png
    - assets/images/vuesax-bulk-wallet.png
    - assets/images/history.png
    - assets/images/wallaet.png
    - assets/images/historyman.png
    - assets/images/checkboxcirclefill.png
    - assets/images/add.png
    - assets/images/img.png
    - assets/images/imgman.png
    - assets/images/cardesign.png
    - assets/images/logowhite.png
    - assets/images/arrow_simple_chock.png
    - assets/images/heart.png
    - assets/images/blutooth.png
    - assets/images/clock.png
    - assets/images/report.png
    - assets/images/location.png
    - assets/images/userphotoright.png
    - assets/images/rating.png
    - assets/images/medal_star.png
    - assets/images/message.png
    - assets/images/gmail.png
    - assets/images/call.png
    - assets/images/whatsapp.png
    - assets/images/messagephoto.png
    - assets/images/medal_star_blue.png
    - assets/images/messagesmall.png
    - assets/images/send.png
    - assets/images/messageanswer.png
    - assets/images/arrow-right.png
    - assets/images/arrow-left.png
    - assets/images/cancel.png
    - assets/images/dollar-square.png
    - assets/images/gallery.png
    - assets/images/more-square.png
    - assets/images/flag.png
    - assets/images/dollar.png
    - assets/images/checkbox-circle-fill.png
    - assets/images/rate.png
    - assets/images/ratingbigsize.png
    - assets/images/report_black.png
    - assets/images/money_forbidden.png
    - assets/images/message_remove.png
    - assets/images/forbidden.png
    - assets/images/box_remove.png
    - assets/images/shield-cross.png
    - assets/images/rating_.png
    - assets/images/visa_PNG4.png
    - assets/images/bank.png
    - assets/images/mada.png
    - assets/images/vuesax.png
    - assets/images/list.png
    - assets/images/location_city.png
    - assets/images/filter.png
    - assets/images/element_equal.png
    - assets/images/store.png
    - assets/images/eye.png
    - assets/images/price.png
    - assets/images/special.png
    - assets/images/vip.png
    - assets/images/magicpen.png
    - assets/images/close-circle.png
    - assets/images/chart.png
    - assets/images/delete.png
    - assets/images/vuesaxbulkshopremove.png
    - assets/images/eye.png
    - assets/images/addwhite.png
    - assets/images/minus.png
    - assets/images/usersmall.png
    - assets/images/lock.png
    - assets/images/shield-tick.png
    - assets/images/lamp.png
    - assets/images/flagtwo.png
    - assets/images/link.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/twitter.png
    - assets/images/verify.png
    - assets/images/map.png
    - assets/images/vuesax-bold-heart.jpg
    - assets/images/vuesax-bold-heart-fav.jpg
    - assets/images/banner.png
    - assets/images/ticket-discount.png

    # - assets/images/money_forbidden.png
    # - assets/images/money_forbidden.png
    - assets/images/adv_buy.png
    - assets/images/ratingempty.png
    # - assets/images/money_forbidden.png
    # - assets/images/money_forbidden.png
    # - assets/images/money_forbidden.png
    # - assets/images/money_forbidden.png
    # - assets/images/money_forbidden.png
    # - assets/images/money_forbidden.png
    # - assets/images/money_forbidden.png
    # - assets/images/money_forbidden.png
    # - assets/images/money_forbidden.png
    - assets/images/element.png
    - assets/images/driving.png
    - assets/images/bus.png
    - assets/images/car.png
    - assets/images/group.png
    - assets/images/gas-station.png
    - assets/images/smart-car.png
    #   - Assets/images/b3f932e530491c48bc99ee4502d70482.png

  fonts:
    - family: RB
      fonts:
        - asset: assets/fonts/RB-Bold.ttf
        - asset: assets/fonts/RB-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
